#!C:\Python39\python.exe
print("Content-type: text/html")
print("")
print("<html lang='en'>")
print("")
print("<head>")
print("	<meta charset='utf-8'>")
print("	<title>Main Page</title>")
print("	<meta name='description' content='The nuke-ops Project'/>")
print("	<link rel='icon' href='resources/images/nstrat.ico'>")
print("	<meta name='google-site-verification' content='7e-wRSGeUMNQA-BhZJY0oofBHBAiQaRTso3AeU4PhbU' />")
print("	<link rel='stylesheet' href='resources/stylesheet/style.css'>")
print("	<meta name='viewport' content='width=device-width, initial-scale=1'>")
print("	<link href='https://fonts.googleapis.com/css?family=Roboto&display=swap' rel='stylesheet'>")
print("	<style>")
print("		@font-face{font-family:joystixmonospace;src:url('resources/fonts/joystix_monospace-webfont.woff')}")
print("	</style>")
print("</head>")
print("")
print("<body>")
print("	<a href='ss13/'>")
print("		<button class='redirect-button' id='neon'><i>SS13</i> ")
print("		</button></a>")
print("	<a href='https://discord.gg/bxgeRPq'>")
print("		<button class='redirect-button' id='neon'><i>DISCORD</i> ")
print("		</button></a>")
print("	<a href='warframe/'>")
print("		<button class='redirect-button' id='neon'><i>WARFRAME</i> ")
print("		</button></a>")
print("	<a href='https://invite.teamspeak.com/nukeops.com/'>")
print("		<button class='redirect-button' id='neon'><i>TEAMSPEAK3</i> ")
print("		</button></a>")
print("</body>")
print("")
print("</html>")
