#!C:\Python39\python.exe
print("Content-type: text/html")
print("")
print("<html lang='en'>")
print("")
print("   <head>")
print("      <meta charset='utf-8'>")
print("      <meta name='description' content='Nuke Ops-ss13'>")
print("      <title>Uplink</title>")
print("      <link rel='icon' href='../resources/images/nstrat.ico'>")
print("      <meta name='google-site-verification' content='7e-wRSGeUMNQA-BhZJY0oofBHBAiQaRTso3AeU4PhbU' />")
print("      <link rel='stylesheet' href='../resources/stylesheet/style.css'>")
print("      <meta name='viewport' content='width=device-width, initial-scale=1'>")
print("      <link href='https://fonts.googleapis.com/css?family=Roboto&display=swap' rel='stylesheet'>")
print("      <link href='https://fonts.googleapis.com/css?family=Open+Sans&display=swap' rel='stylesheet'>")
print("      <style>@font-face{font-family:joystixmonospace;src:url('../resources/fonts/joystix_monospace-webfont.woff')}</style>")
print("   </head>")
print("   <body>")
print("   		<a href='../'> <button id='neon'><i>BACK</i> </button> </a>")
print("   		<a href='rules/'> <button id='neon'><i>RULES</i></button></a>")
print("   		<a href='byond://nukeops.com:1337'> <button id='neon'><i>SERVER</i></button></a>")
print("   		<a href='https://nukeops.com/ss13/wiki'> <button id='neon'><i>WIKI</i></button></a>")
print("   		<a href='https://github.com/nuke-ops/Nostra-13'><button id='neon'><i>GITHUB</i></button></a>")
print("   		<a href='stats'><button id='neon'><i>STATS</i></button> </a>")
print("   </body>")
print("</html>")
